services:
  app:
    cpus: 4
    mem_limit: 8g
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        - PY_VER=${PY_VER:-3.11}
        - DISTRO=${DISTRO:-buster}
    image: datajoint/element_array_ephys:latest
    environment:
      - DJ_PUBLIC_S3_LOCATION=djhub.vathes.datapub.elements:/workflow-array-ephys-benchmark/v2
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - ..:/workspaces:cached
      - docker_data:/var/lib/docker # persist docker images
    user: root
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
volumes:
  docker_data:
